openapi: 3.0.1
info:
  title: BSCS_Sample_Dynamic_API
  description: API Definition of BSCS_Sample_Dynamic_API
  version: 1.0.0
servers:
- url: http://localhost:8290/BSCS/GenericApi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
