openapi: 3.0.1
info:
  title: ProcedureCall_API
  description: API Definition of ProcedureCall_API
  version: 1.0.0
servers:
- url: http://localhost:8290/procedure_call
paths:
  /:
    get:
      responses:
        default:
          description: Default response
