openapi: 3.0.1
info:
  title: PROPERTlOADER
  description: API Definition of PROPERTlOADER
  version: 1.0.0
servers:
- url: http://localhost:8290/PROPERTYLOADER
paths:
  /:
    get:
      responses:
        default:
          description: Default response
