openapi: 3.0.1
info:
  title: sampleSecurityAPI
  description: API Definition of sampleSecurityAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/SecurityAPI
paths:
  /:
    get:
      responses:
        default:
          description: Default response
