openapi: 3.0.1
info:
  title: PHP_decode_API
  description: API Definition of PHP_decode_API
  version: 1.0.0
servers:
- url: http://localhost:8290/php-decode
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
