openapi: 3.0.1
info:
  title: mock_api
  description: API Definition of mock_api
  version: 1.0.0
servers:
- url: http://localhost:8290/mock_api
paths:
  /:
    post:
      responses:
        default:
          description: Default response
