openapi: 3.0.1
info:
  title: NotificationManagementSystem_API
  description: API Definition of NotificationManagementSystem_API
  version: 1.0.0
servers:
- url: http://localhost:8290/notify
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
