openapi: 3.0.1
info:
  title: MultiLanguageSupport_API
  description: API Definition of MultiLanguageSupport_API
  version: 1.0.0
servers:
- url: http://localhost:8290/lang-convert
paths:
  /:
    get:
      responses:
        default:
          description: Default response
