openapi: 3.0.1
info:
  title: FaultSeqTest_API
  description: API Definition of FaultSeqTest_API
  version: 1.0.0
servers:
- url: http://localhost:8290/fault-seq-test
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
