openapi: 3.0.1
info:
  title: AddressRead_API
  description: API Definition of AddressRead_API
  version: 1.0.0
servers:
- url: http://localhost:8290/custAddress
paths:
  /:
    post:
      responses:
        default:
          description: Default response
