openapi: 3.0.1
info:
  title: Local-entries-check
  description: API Definition of Local-entries-check
  version: 1.0.0
servers:
- url: http://localhost:8290/local-entries
paths:
  /:
    get:
      responses:
        default:
          description: Default response
