openapi: 3.0.1
info:
  title: RegPropertiesCheck
  description: API Definition of RegPropertiesCheck
  version: 1.0.0
servers:
- url: http://localhost:8290/Registry
paths:
  /:
    get:
      responses:
        default:
          description: Default response
