openapi: 3.0.1
info:
  title: SequenceCalling_API
  description: API Definition of SequenceCalling_API
  version: 1.0.0
servers:
- url: http://localhost:8290/callingSeq
paths:
  /:
    get:
      responses:
        default:
          description: Default response
