openapi: 3.0.1
info:
  title: CustomerValidation_API
  description: API Definition of CustomerValidation_API
  version: 1.0.0
servers:
- url: http://localhost:8290/validate_customer
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
