openapi: 3.0.1
info:
  title: dynamicNMSSeqApi
  description: API Definition of dynamicNMSSeqApi
  version: 1.0.0
servers:
- url: http://localhost:8290/nms
paths:
  /:
    post:
      responses:
        default:
          description: Default response
